name: build sabnzbd docker mod

on:
  push:
    branches:
      - master
    paths:
      - 'docker-mods/sabnzbd/**'
      - '.github/workflows/build-sabnzbd-mod.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push
        run: |
          tag="ghcr.io/${{ github.repository_owner }}/theme.park:sabnzbd"
          tag="${tag,,}"
          docker build docker-mods/sabnzbd --tag "$tag"
          docker push "$tag"
